version: '3.1'

services:
  db:
    image: mysql:8.0.33
    container_name: db
    restart: always
    secrets:
      - mysql_root
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root
      MYSQL_DATABASE: donuts
      TZ: "Europe/London"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    network_mode: "host"

  voyager_donuts:
    container_name: voyager_donuts
    build:
      context: .
      dockerfile: Dockerfile
    image: voyager_donuts
    network_mode: "host"
    environment:
      TZ: "Europe/London"
    volumes:
      - c:/Users/user/Documents/Voyager/DonutsCalibration:/voyager_calibration
      - c:/Users/user/Documents/Voyager/DonutsLog:/voyager_log
      - c:/Users/user/Documents/Voyager/DonutsData:/voyager_data
      - c:/Users/user/Documents/Voyager/DonutsReference:/voyager_reference

volumes:
  mysql-data:

secrets:
  mysql_root:
    file: ./secrets/mysql_root
